"""Add Supabase storage support

Revision ID: 5b95aa8d7880
Revises: 9efcc1f82b81
Create Date: 2025-11-28 16:26:58.242138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b95aa8d7880'
down_revision = '9efcc1f82b81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_data_sources', sa.Column('storage_type', sa.String(length=20), nullable=True))
    op.add_column('external_data_sources', sa.Column('supabase_url', sa.String(length=500), nullable=True))
    op.add_column('external_data_sources', sa.Column('supabase_key_encrypted', sa.Text(), nullable=True))
    op.add_column('external_data_sources', sa.Column('supabase_bucket', sa.String(length=100), nullable=True))
    op.add_column('external_data_sources', sa.Column('file_path_prefix', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_data_sources', 'file_path_prefix')
    op.drop_column('external_data_sources', 'supabase_bucket')
    op.drop_column('external_data_sources', 'supabase_key_encrypted')
    op.drop_column('external_data_sources', 'supabase_url')
    op.drop_column('external_data_sources', 'storage_type')
    # ### end Alembic commands ###
