"""Add external data sources

Revision ID: 9efcc1f82b81
Revises: 002
Create Date: 2025-11-28 16:10:15.729547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efcc1f82b81'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ministry_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('file_column', sa.String(length=100), nullable=True),
    sa.Column('filename_column', sa.String(length=100), nullable=True),
    sa.Column('metadata_columns', sa.JSON(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_frequency', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('total_documents_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_data_sources_id'), 'external_data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_external_data_sources_ministry_name'), 'external_data_sources', ['ministry_name'], unique=False)
    op.create_index(op.f('ix_external_data_sources_name'), 'external_data_sources', ['name'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documents_fetched', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_logs_source_id'), 'sync_logs', ['source_id'], unique=False)
    op.drop_index('idx_department', table_name='document_metadata')
    op.drop_index('idx_document_id', table_name='document_metadata')
    op.drop_index('idx_document_type', table_name='document_metadata')
    op.drop_index('idx_embedding_status', table_name='document_metadata')
    op.drop_index('idx_keywords_gin', table_name='document_metadata', postgresql_using='gin')
    op.drop_index('idx_metadata_status', table_name='document_metadata')
    op.create_index(op.f('ix_document_metadata_department'), 'document_metadata', ['department'], unique=False)
    op.create_index(op.f('ix_document_metadata_document_type'), 'document_metadata', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_metadata_embedding_status'), 'document_metadata', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_document_metadata_id'), 'document_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_document_metadata_metadata_status'), 'document_metadata', ['metadata_status'], unique=False)
    op.create_unique_constraint(None, 'document_metadata', ['document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_metadata', type_='unique')
    op.drop_index(op.f('ix_document_metadata_metadata_status'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_embedding_status'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_document_type'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_department'), table_name='document_metadata')
    op.create_index('idx_metadata_status', 'document_metadata', ['metadata_status'], unique=False)
    op.create_index('idx_keywords_gin', 'document_metadata', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_embedding_status', 'document_metadata', ['embedding_status'], unique=False)
    op.create_index('idx_document_type', 'document_metadata', ['document_type'], unique=False)
    op.create_index('idx_document_id', 'document_metadata', ['document_id'], unique=False)
    op.create_index('idx_department', 'document_metadata', ['department'], unique=False)
    op.drop_index(op.f('ix_sync_logs_source_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_external_data_sources_name'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_ministry_name'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_id'), table_name='external_data_sources')
    op.drop_table('external_data_sources')
    # ### end Alembic commands ###
