"""add chat history tables

Revision ID: e6175865ca0d
Revises: 5b95aa8d7880
Create Date: 2025-12-01 09:16:09.173356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6175865ca0d'
down_revision = '5b95aa8d7880'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_thread_id'), 'chat_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Values: login, logout, upload_document, user_approved, user_rejected, document_approved, document_rejected, role_changed, search_query',
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index('ix_bookmarks_user_id', table_name='bookmarks')
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.alter_column('documents', 'visibility_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Values: public, institution_only, restricted, confidential',
               existing_nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('documents', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Values: pending, approved, rejected',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_documents_institution_id', table_name='documents')
    op.drop_index('ix_documents_visibility_level', table_name='documents')
    op.drop_constraint('documents_approved_by_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_institution_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_uploader_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'documents', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['uploader_id'], ['id'])
    op.alter_column('institutions', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Values: university, government_dept, ministry',
               existing_nullable=False)
    op.alter_column('institutions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Values: developer, moe_admin, university_admin, document_officer, student, public_viewer',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_institution_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_institution_id_fkey', 'users', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Values: developer, moe_admin, university_admin, document_officer, student, public_viewer',
               existing_nullable=False)
    op.alter_column('institutions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('institutions', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Values: university, government_dept, ministry',
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_uploader_id_fkey', 'documents', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('documents_institution_id_fkey', 'documents', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('documents_approved_by_fkey', 'documents', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_documents_visibility_level', 'documents', ['visibility_level'], unique=False)
    op.create_index('ix_documents_institution_id', 'documents', ['institution_id'], unique=False)
    op.alter_column('documents', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Values: pending, approved, rejected',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('documents', 'visibility_level',
               existing_type=sa.VARCHAR(length=50),
               comment='Values: public, institution_only, restricted, confidential',
               existing_nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.create_index('ix_bookmarks_user_id', 'bookmarks', ['user_id'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Values: login, logout, upload_document, user_approved, user_rejected, document_approved, document_rejected, role_changed, search_query',
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_updated_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_thread_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
