export const ROLES = {
  DEVELOPER: 'Developer',
  MOE_ADMIN: 'MoE Admin',
  UNIVERSITY_ADMIN: 'University Admin',
  DOCUMENT_OFFICER: 'Document Officer',
  STUDENT_VIEWER: 'Student Viewer',
  PUBLIC_VIEWER: 'Public Viewer',
};

export const ADMIN_ROLES = [ROLES.DEVELOPER, ROLES.MOE_ADMIN, ROLES.UNIVERSITY_ADMIN];
export const DOCUMENT_MANAGER_ROLES = [ROLES.DEVELOPER, ROLES.MOE_ADMIN, ROLES.UNIVERSITY_ADMIN, ROLES.DOCUMENT_OFFICER];
export const VIEWER_ROLES = [ROLES.STUDENT_VIEWER, ROLES.PUBLIC_VIEWER];
export const ALL_ROLES = Object.values(ROLES);
